name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.21
      - run: go test ./...

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.21
      - run: go build -o todo-cli-go .
      - run: echo "VERSION=$(git describe --tags --abbrev=0)" > .version
      - run: go build -ldflags="-X 'main.Version=$(cat .version)'" -o todo-cli-go .
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: todo-cli-go
          path: todo-cli-go